{
  config,
  pkgs,
  ...
}:
let
  pywalfoxManifest = builtins.toJSON {
    name = "pywalfox";
    description = "Automatically theme your browser using the colors generated by Pywal";
    path = "${pkgs.pywalfox-native}/bin/pywalfox";
    type = "stdio";
    allowed_extensions = [ "pywalfox@frewacom.org" ];
  };
in
{
  home.packages = with pkgs; [
    # firefoxpwa
    pywalfox-native
  ];

  home.file.".mozilla/native-messaging-hosts/pywalfox.json".text = pywalfoxManifest;
  xdg.configFile."mozilla/native-messaging-hosts/pywalfox.json".text = pywalfoxManifest;

  programs.firefox = {
    enable = true;
    configPath = "${config.xdg.configHome}/mozilla/firefox";
    nativeMessagingHosts = [
      # pkgs.firefoxpwa
    ];

    package = pkgs.firefox.overrideAttrs (old: {
      postFixup = (old.postFixup or "") + ''
        wrapProgram $out/bin/firefox --set GTK_USE_PORTAL 1
      '';
    });

    profiles.default = {
      extensions.packages = with pkgs.nur.repos.rycee.firefox-addons; [
        bitwarden
        darkreader
        export-cookies-txt
        mal-sync
        pywalfox
        tampermonkey
        ublock-origin
      ];

      settings = {
        "gfx.webrender.all" = true;
        "media.ffmpeg.vaapi.enabled" = true;
        "media.hardware-video-decoding.force-enabled" = true;
        "widget.dmabuf.force-enabled" = true;
        "layers.acceleration.force-enabled" = true;

        "signon.rememberSignons" = false;
        "browser.download.dir" = "${config.home.homeDirectory}/Downloads";
        "browser.download.skipConfirmLaunchExecutable" = true;
        "browser.translations.mostRecentTargetLanguages" = "en";
        "browser.translations.neverTranslateLanguages" = "he";
      };
    };
  };
}
