# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "nvidia"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidia_drm"
  ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelParams = [
    "acpi_enforce_resources=lax"
    "mem_sleep_default=deep"
    "nvidia-drm.modeset=1"
    "nvidia-drm.fbdev=1"
    "iommu=pt"
    "module_blacklist=amdgpu"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "coretemp"
    "it87"
  ];
  boot.extraModprobeConfig = ''
    options it87 ignore_resource_conflict=1

    # Fix NVIDIA Sleep/Wake (You need these for mem_sleep_default=deep!)
    options nvidia NVreg_PreserveVideoMemoryAllocations=1
    options nvidia NVreg_TemporaryFilePath=/var/tmp
    options nvidia NVreg_EnableGpuFirmware=0 
  '';
  # Fixed the bluetooth connection refused - 0x0003 security block error I had with my DualSense controller
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.extraModulePackages = with config.boot.kernelPackages; [
    (lib.hiPrio (
      it87.overrideAttrs (old: {
        postInstall = (old.postInstall or "") + ''
          # Compress the module to match standard NixOS behavior
          find $out -name '*.ko' -exec xz {} \;

          # Delete the module metadata to prevent it from overwriting the main kernel's metadata
          rm -f $out/lib/modules/*/modules.*
        '';
      })
    ))
  ];
  # boot.kernelPatches = [
  #   {
  #     name = "disable-it87";
  #     patch = null;
  #     structuredExtraConfig = with lib.kernel; {
  #       SENSORS_IT87 = no;
  #     };
  #   }
  # ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f2d9e5cc-0f37-4645-abcb-02a43e019297";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1F71-F315";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/01DC5BB7CE86B630";
    fsType = "ntfs-3g";
    options = [
      "defaults"
      "nofail"
      "windows_names"
      "locale=en_US.utf8"
      "uid=1000"
      "gid=100"
      "umask=0022"
      "x-gvfs-show"
      "x-gvfs-name=Windows"
    ];
  };

  fileSystems."/mnt/T7Shield" = {
    device = "/dev/disk/by-uuid/68E8976DE8973870";
    fsType = "ntfs-3g";
    options = [
      "defaults"
      "nofail"
      "windows_names"
      "locale=en_US.utf8"
      "uid=1000"
      "gid=100"
      "umask=0022"
      "x-gvfs-show"
      "x-gvfs-name=T7 Shield"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = with pkgs; [
    linux-firmware
  ];
}
