# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelParams = [ 
    "acpi_enforce_resources=lax"
    # AMD/NVIDIA suspend fixes
    "amd_iommu=on"
    "iommu=pt"
    "pcie_aspm=off"  # Fix for AMD suspend issues
    "mem_sleep_default=deep"  # Enable deep sleep
    "processor.max_cstate=1"  # Limit C-states to prevent issues
    # NVIDIA specific
    "nvidia-drm.modeset=1"
    "nvidia-drm.fbdev=1"
    "ibt=off"  # Disable Intel Indirect Branch Tracking (can cause issues with NVIDIA)
  ];
  boot.kernelModules = [
    "kvm-amd"
    "coretemp"
    "it87"
  ];
  boot.extraModprobeConfig = ''
    options it87 force_id=0x8689,0x8883 ignore_resource_conflict=1
    # NVIDIA suspend/resume fixes
    options nvidia NVreg_PreserveVideoMemoryAllocations=1
    options nvidia NVreg_TemporaryFilePath=/var/tmp
    options nvidia NVreg_EnableGpuFirmware=0
  '';
  boot.extraModulePackages = with config.boot.kernelPackages; [
    it87
  ];
  boot.kernelPatches = lib.singleton {
    name = "disable-it87";
    patch = null;
    structuredExtraConfig = with lib.kernel; {
      SENSORS_IT87 = no;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2d6ec19f-a111-4b30-992b-d9df674ea3a2";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5A52-2D81";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/38442F8B442F4B48";
    fsType = "ntfs-3g";
    options = [
      "defaults"
      "windows_names"
      "locale=en_US.utf8"
      "x-gvfs-show"
      "x-gvfs-name=Windows"
    ];
  };

  fileSystems."/mnt/arch" = {
    device = "/dev/disk/by-uuid/a68f15b0-0428-45fc-9e9d-67d74e5fd842";
    fsType = "ext4";
    options = [
      "defaults"
      "noatime"
      "x-gvfs-show"
      "x-gvfs-name=Arch"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a7b09eb8-86da-45ef-9903-b46180f1703d"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
